import { ReactNode } from 'react'

export const icons = { dashboard: '▦', suppliers: '♙', products: '◈', network: '⌘', simulator: '◉', risk: '⚠', search: '⌕', database: '●' }
export function LoadingSkeleton({ className = 'h-24' }: { className?: string }) { return <div className={`animate-pulse rounded-xl bg-slate-200/80 ${className}`} /> }
export function LoadingCards({ count = 4 }: { count?: number }) { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({length:count}).map((_,i)=><LoadingSkeleton key={i} className="h-32"/>)}</div> }
export function EmptyState({ title='Nothing to show yet', detail='Try changing your filters or explore another area.', action }: {title?:string;detail?:string;action?:ReactNode}) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center"><span className="grid mx-auto h-11 w-11 place-items-center rounded-xl bg-slate-100 text-xl text-slate-500">◌</span><h3 className="mt-4 font-semibold text-slate-900">{title}</h3><p className="mx-auto mt-1 max-w-sm text-sm text-slate-500">{detail}</p>{action&&<div className="mt-5">{action}</div>}</div> }
export function ErrorState({retry}:{retry?:()=>void}) { return <div role="alert" className="rounded-2xl border border-red-100 bg-red-50 px-6 py-9 text-center"><span className="text-xl text-red-600">!</span><h3 className="mt-2 font-semibold text-slate-900">Unable to load supply data</h3><p className="mt-1 text-sm text-slate-600">Please try again. If the issue continues, check the data connection.</p>{retry&&<button onClick={retry} className="btn-secondary mt-5">Try again</button>}</div> }
export function StatusBadge({children}:{children:ReactNode}) { const text=String(children).toLowerCase();const styles=text==='active'?'bg-green-50 text-green-700 ring-green-600/20':text==='inactive'?'bg-slate-100 text-slate-600 ring-slate-500/20':'bg-amber-50 text-amber-700 ring-amber-600/20';return <span className={`badge ring-1 ${styles}`}>{children}</span> }
export function RiskBadge({children}:{children:ReactNode}) { const text=String(children).toLowerCase();const styles=text==='critical'||text==='high'?'bg-red-50 text-red-700 ring-red-600/20':text==='medium'||text==='affected'?'bg-amber-50 text-amber-700 ring-amber-600/20':text==='low'?'bg-blue-50 text-blue-700 ring-blue-600/20':'bg-teal-50 text-teal-700 ring-teal-600/20';return <span className={`badge ring-1 ${styles}`}>{children}</span> }
export function StatCard({label,value,icon,tone='navy',trend}:{label:string;value:number;icon:string;tone?:'navy'|'teal'|'red'|'amber'|'blue'|'rose';trend:string}) { const colors={navy:'bg-[#EFF6FF] text-[#2563EB]',teal:'bg-[#F0FDFA] text-[#0F9D9A]',red:'bg-[#FEF2F2] text-[#DC2626]',amber:'bg-[#FFFBEB] text-[#D97706]',blue:'bg-[#EFF6FF] text-[#2563EB]',rose:'bg-[#FFF1F2] text-[#E11D48]'};return <article className={`card stat-card stat-${tone} group`}><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight text-slate-900">{value}</p></div><span className={`grid h-10 w-10 place-items-center rounded-xl text-lg ${colors[tone]}`}>{icon}</span></div><p className="mt-4 text-xs font-medium text-slate-500">{trend}</p></article> }
export function PageTitle({eyebrow,title,children}:{eyebrow:string;title:string;children?:ReactNode}) { return <div className="page-title mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-teal-700">{eyebrow}</p><h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">{title}</h1></div>{children}</div> }
export function GraphLegend(){return <div className="flex flex-wrap gap-x-4 gap-y-2 text-xs text-slate-600" aria-label="Graph legend">{[['Supplier','bg-blue-500'],['Component','bg-violet-500'],['Product','bg-teal-500'],['Warehouse','bg-amber-500'],['Region','bg-slate-500'],['Disrupted','bg-red-600']].map(([label,color])=><span className="flex items-center gap-1.5" key={label}><i className={`h-2.5 w-2.5 rounded-full ${color}`}/>{label}</span>)}</div> }
export function Toast({message,onClose}:{message:string;onClose:()=>void}) { return <div role="status" className="fixed bottom-5 right-5 z-50 flex max-w-sm items-center gap-3 rounded-xl border border-teal-200 bg-white px-4 py-3 text-sm font-medium text-slate-700 shadow-xl"><span className="grid h-6 w-6 place-items-center rounded-full bg-teal-50 text-teal-700">✓</span><span>{message}</span><button onClick={onClose} aria-label="Dismiss notification" className="ml-auto text-slate-400 hover:text-slate-700">×</button></div> }

// Compatibility aliases keep page code concise while using the shared enterprise badge/empty components.
export function Badge({children, tone}: {children:ReactNode; tone?:string}) { return <RiskBadge>{children}</RiskBadge> }
export const Empty = EmptyState
